#!/usr/bin/env bash
set -e

root_path=$(realpath .)
template_path="$(root_path)/template.yml"

echo "== deploy secrets manager mask"

STACK_NAME="aws-sm-mask"

aws cloudformation deploy \
    --template-file "${template_path}" \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameters-override MyPassword="!645321gnitesT" \
    --no-execute-changeset \
    --region ca-central-1 \
    --stack-name $STACK_NAME