#!/usr/bin/env bash

echo "== deploy ec2"

STACK_NAME="aws-asg-ec2-basic"

aws cloudformation deploy --template-file template.yml --capabilities CAPABILITY_NAMED_IAM --no-execute-changeset --region ca-central-1 --stack-name $STACK_NAME