#!/usr/bin/env bash


# Check if the argument is not provided
if [-z "$1"]; then
    echo "Argument not provided."
else
    export VPC_ID="$1"
fi

if [-z "$2"]; then
    echo "Argument not provided."
else
    export IGW_ID="$2"
fi

if [-z "$3"]; then
    echo "Argument not provided."
else
    export SUBNET_ID="$3"
fi

if [-z "$4"]; then
    echo "Argument not provided."
else
    export ASSOC_ID="$4"
fi


if [-z "$5"]; then
    echo "Argument not provided."
else
    export RT_ID="$5"
fi

# Dettach IGW
aws ec2 detach-internet-gateway --internet-gateway $IGW_ID --vpc-id $VPC_ID

# Delete IGW
aws ec2 delete-internet-gateway $IGW_ID

# Disassociate subnet from route table
aws ec2 disassociate-route-table --association-id $ASSOC_ID

# Delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

# Delete route table
# aws ec2 delete-route-table --route-table-id $RT_ID

# Delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID
