#!/usr/bin/env bash

echo "== deploy ec2 instance to interract with redis"

STACK_NAME="ec2-4-redis"

aws cloudformation deploy --template-file template.yml --capabilities CAPABILITY_NAMED_IAM --no-execute-changeset --region ca-central-1 --stack-name $STACK_NAME