AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Launch a simple EC2 to test VPCs

Resources:
  InlineLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: python3.12
      PackageType: Zip
      CodeUri: "./function/"
