AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda function example with container

Resources:
  InlineLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: ../
      DockerFile: Dockerfile
    Properties:
      PackageType: Image
